version: '2'

services:

  consul:
    image: mscblog/consul:latest
    ports:
      - 5300:8080
    networks:
      - main

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3000:80
    environment:
      SERVICE_DISCOVERY_HOST: consul
      SERVICE_DISCOVERY_PORT: 8080
      PORT: 80
      VCAP_APPLICATION: '{"uris": ["user-api"]}'
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3001:3000
    environment:
      SERVICE_DISCOVERY_HOST: consul
      SERVICE_DISCOVERY_PORT: 8080
      PORT: 80
      VCAP_APPLICATION: '{"uris": ["article-api"]}'
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  comments-api:
    image: mscblog/comments-api:latest
    ports:
      - 3002:3000
    environment:
      SERVICE_DISCOVERY_HOST: consul
      SERVICE_DISCOVERY_PORT: 8080
      PORT: 80
      VCAP_APPLICATION: '{"uris": ["comments-api"]}'
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

networks:
  main: