version: '2'

services:

  consul:
    image: mscblog/consul:latest
    ports:
      - 5300:8080
    networks:
      - main

  fakes3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569
    networks:
      - main

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3000:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: localhost:3000
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3001:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: localhost:3001
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  comments-api:
    image: mscblog/comments-api:latest
    ports:
      - 3002:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: localhost:3002
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  upload-api:
    image: mscblog/upload-api:latest
    restart: always
    ports:
      - 3003:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: http://upload-api:3000
      ACCESS_KEY_ID: abc123
      SECRET_ACCESS_KEY: abc123
      S3_BUCKET: blog-test
      S3_URL: fakes3:4569
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

  avatar-api:
    image: mscblog/avatar-api:latest
    restart: always
    ports:
      - 3004:3000
    environment:
      SERVICE_DISCOVERY_HOST: ${consul_host}
      SERVICE_DISCOVERY_PORT: ${consul_port}
      HOSTNAME: http://localhost:3004
    networks:
      - main
    command: >
      /bin/bash -c "sleep 5; node ."

networks:
  main: