version: '3'

services:

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - mscblog
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3001:3000
    networks:
      main:
        aliases:
          - mscblog
    command: >
      /bin/bash -c "sleep 5; node ."

networks:
  main:

volumes:
  yarn:
